### ISSUE TITLE
[吹き出し]テーマ追加：LINE（フラット）

### ISSUE THREAD

**Issue by kinformation** [kinformation/grav-plugin-speech-bubble#6]

**Comment by kinformation** [comment]
type=flat

**Comment by kinformation** [comment]
``` CSS
.sb-bubble {
    position: relative;
    background: #85E249;
    border-radius: 1em;
    padding: .2em 1em;
    max-width: 70%;
}

.sb-bubble:after,
.sb-bubble:before {
    top: 1.2em;
    border: solid transparent;
    content: " ";
    height: 0;
    width: 0;
    position: absolute;
    pointer-events: none;
}


/* right side bubble */


.sb-bubble-right:before {
    left: 100%;
    height:12px;
    width:6px;
    background: #85E249;
    border-radius: 0 16px 16px 0;
    margin: -23px 0 0 -3px;
}

.sb-bubble-right:after {
    left: 100%;
    height:12px;
    width:6px;
    background: #ffffff;
    border-radius: 0 16px 16px 0;
    margin: -30px 0 0 -3px;
}

/* left side bubble */

.sb-bubble-left:before {
    right: 100%;
    height:12px;
    width:6px;
    background: #85E249;
    border-radius: 16px 0 0 16px;
    margin: -23px -3px 0 0;
}

.sb-bubble-left:after {
    right: 100%;
    height:12px;
    width:6px;
    background: #ffffff;
    border-radius: 16px 0 0 16px;
    margin: -30px -3px 0 0;
}
```
